// <auto-generated />
using System;
using BeFirst.WebAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeFirst.WebAPI.Migrations
{
    [DbContext(typeof(BeFirstContext))]
    partial class BeFirstContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BeFirst.WebAPI.Database.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KorisničkoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UlogaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UlogaId");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KorisničkoIme = "Admin",
                            PasswordHash = "FtJdX+0+S7XwnwHgLkPxTUygj08=",
                            PasswordSalt = "zQizqXl1hfbL3Yg/g3OteA==",
                            UlogaId = 1
                        },
                        new
                        {
                            Id = 2,
                            KorisničkoIme = "BeFirstKorisnik",
                            PasswordHash = "GfOIoJsRZ3acjo73luCKvqfwH34=",
                            PasswordSalt = "tKv10dENHhM7HEA8AptZWA==",
                            UlogaId = 2
                        },
                        new
                        {
                            Id = 3,
                            KorisničkoIme = "Hazim",
                            PasswordHash = "HuiOKkk2juGXgaR155oZLYuhrco=",
                            PasswordSalt = "+98TCK7Prn74upr2wFnSRA==",
                            UlogaId = 2
                        },
                        new
                        {
                            Id = 4,
                            KorisničkoIme = "BeFirstUposlenik",
                            PasswordHash = "txoZ27+iGZVFyqi8dj4tpXL3yTk=",
                            PasswordSalt = "i7dJDt4f375NU0HgYbE46w==",
                            UlogaId = 3
                        },
                        new
                        {
                            Id = 5,
                            KorisničkoIme = "BeFirstServiser",
                            PasswordHash = "iZaqi/tQukIrLUXGT3s3gGGUJP0=",
                            PasswordSalt = "SrY3Tqxi65mhzoZW8PdPiA==",
                            UlogaId = 4
                        },
                        new
                        {
                            Id = 6,
                            KorisničkoIme = "AjlaBise",
                            PasswordHash = "AB3LuS0MYU/1zWNgWjJE0rExjeU=",
                            PasswordSalt = "+98TCK7Prn74upr2wFnSRA==",
                            UlogaId = 2
                        },
                        new
                        {
                            Id = 7,
                            KorisničkoIme = "ArmanBise",
                            PasswordHash = "DsTh0j1/E4esSNjRCn+jtSjx1AI=",
                            PasswordSalt = "+98TCK7Prn74upr2wFnSRA==",
                            UlogaId = 2
                        },
                        new
                        {
                            Id = 8,
                            KorisničkoIme = "MahirSkula",
                            PasswordHash = "bKIQzimofw5cMPiGHClHU4mRYH0=",
                            PasswordSalt = "+98TCK7Prn74upr2wFnSRA==",
                            UlogaId = 2
                        },
                        new
                        {
                            Id = 9,
                            KorisničkoIme = "DzanisBrkan",
                            PasswordHash = "1lehabhntsH2RF/Kd0ZhReNzwao=",
                            PasswordSalt = "+98TCK7Prn74upr2wFnSRA==",
                            UlogaId = 2
                        },
                        new
                        {
                            Id = 10,
                            KorisničkoIme = "AhmedHazimovic",
                            PasswordHash = "okDfATqJgsrBnAlvuSowfME5oww=",
                            PasswordSalt = "+98TCK7Prn74upr2wFnSRA==",
                            UlogaId = 2
                        },
                        new
                        {
                            Id = 11,
                            KorisničkoIme = "NedimSendro",
                            PasswordHash = "759xdgzWKH/Rub13mn1WkrelDlo=",
                            PasswordSalt = "i7dJDt4f375NU0HgYbE46w==",
                            UlogaId = 3
                        },
                        new
                        {
                            Id = 12,
                            KorisničkoIme = "LejlaBise",
                            PasswordHash = "4ihCLLBdn4pJUzNSbHgG5GjycqQ=",
                            PasswordSalt = "i7dJDt4f375NU0HgYbE46w==",
                            UlogaId = 3
                        },
                        new
                        {
                            Id = 13,
                            KorisničkoIme = "NikolaLeung",
                            PasswordHash = "NHScnIQQKvDI8Mi7XabO9u+uTy0=",
                            PasswordSalt = "i7dJDt4f375NU0HgYbE46w==",
                            UlogaId = 3
                        });
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Administrator");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            Adresa = "Admin Adresa 1",
                            Ime = "Ajla",
                            Prezime = "Bise"
                        });
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.Internet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brzina")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<float>("Cijena")
                        .HasColumnType("real");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UgovorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UgovorId");

                    b.ToTable("Internet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brzina = "150mbps",
                            Cijena = 75.99f,
                            Naziv = "Internet 1",
                            Opis = "Brz internet haos",
                            UgovorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Brzina = "50mbps",
                            Cijena = 75.99f,
                            Naziv = "Internet 2",
                            Opis = "Brz internet haos",
                            UgovorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Brzina = "150mbps",
                            Cijena = 75.99f,
                            Naziv = "Internet 3",
                            Opis = "Brz internet haos",
                            UgovorId = 1
                        },
                        new
                        {
                            Id = 4,
                            Brzina = "100mbps",
                            Cijena = 75.99f,
                            Naziv = "Internet 4",
                            Opis = "Brz internet haos",
                            UgovorId = 1
                        },
                        new
                        {
                            Id = 5,
                            Brzina = "150mbps",
                            Cijena = 75.99f,
                            Naziv = "Internet 5",
                            Opis = "Brz internet haos",
                            UgovorId = 1
                        });
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId")
                        .HasColumnName("AccountID")
                        .HasColumnType("int");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaketId")
                        .HasColumnName("PaketID")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("UgovorId")
                        .HasColumnName("UgovorID")
                        .HasColumnType("int");

                    b.Property<int>("VrstaKorisnika")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("PaketId");

                    b.HasIndex("UgovorId");

                    b.ToTable("Korisnik");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 2,
                            Adresa = "Korisnik Adresa 1",
                            BrojTelefona = "061222555",
                            DatumRodjenja = new DateTime(1997, 5, 23, 1, 10, 58, 93, DateTimeKind.Local).AddTicks(4066),
                            Email = "korisnik1@befirst.com",
                            Grad = "Mostar",
                            Ime = "KorisnikIme",
                            Komentar = "Bez rijeci",
                            PaketId = 1,
                            Prezime = "KorisnikPrezime",
                            UgovorId = 1,
                            VrstaKorisnika = 4
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 3,
                            Adresa = "Korisnik Adresa 2",
                            BrojTelefona = "061777999",
                            DatumRodjenja = new DateTime(1985, 5, 23, 1, 10, 58, 95, DateTimeKind.Local).AddTicks(9686),
                            Email = "korisnik2@befirst.com",
                            Grad = "Sarajevo",
                            Ime = "Hazim",
                            Komentar = "Ostao bez teksta",
                            PaketId = 1,
                            Prezime = "Hazimovic",
                            UgovorId = 1,
                            VrstaKorisnika = 4
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 6,
                            Adresa = "Korisnik Adresa 3",
                            BrojTelefona = "061777999",
                            DatumRodjenja = new DateTime(1985, 5, 23, 1, 10, 58, 95, DateTimeKind.Local).AddTicks(9768),
                            Email = "korisnik2@befirst.com",
                            Grad = "Sarajevo",
                            Ime = "Ajla",
                            Komentar = "Ostao bez teksta",
                            PaketId = 3,
                            Prezime = "Bise",
                            UgovorId = 3,
                            VrstaKorisnika = 2
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 7,
                            Adresa = "Korisnik Adresa 2",
                            BrojTelefona = "061777999",
                            DatumRodjenja = new DateTime(1985, 5, 23, 1, 10, 58, 95, DateTimeKind.Local).AddTicks(9775),
                            Email = "korisnik2@befirst.com",
                            Grad = "Sarajevo",
                            Ime = "Arman",
                            Komentar = "Ostao bez teksta",
                            PaketId = 3,
                            Prezime = "Bise",
                            UgovorId = 4,
                            VrstaKorisnika = 2
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 8,
                            Adresa = "Korisnik Adresa 2",
                            BrojTelefona = "061777999",
                            DatumRodjenja = new DateTime(1985, 5, 23, 1, 10, 58, 95, DateTimeKind.Local).AddTicks(9781),
                            Email = "korisnik2@befirst.com",
                            Grad = "Sarajevo",
                            Ime = "Mahir",
                            Komentar = "Ostao bez teksta",
                            PaketId = 4,
                            Prezime = "Skula",
                            UgovorId = 3,
                            VrstaKorisnika = 2
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 9,
                            Adresa = "Korisnik Adresa 2",
                            BrojTelefona = "061777999",
                            DatumRodjenja = new DateTime(1985, 5, 23, 1, 10, 58, 95, DateTimeKind.Local).AddTicks(9786),
                            Email = "korisnik2@befirst.com",
                            Grad = "Sarajevo",
                            Ime = "Dzanis",
                            Komentar = "Ostao bez teksta",
                            PaketId = 3,
                            Prezime = "Brkan",
                            UgovorId = 3,
                            VrstaKorisnika = 1
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 10,
                            Adresa = "Korisnik Adresa 2",
                            BrojTelefona = "061777999",
                            DatumRodjenja = new DateTime(1985, 5, 23, 1, 10, 58, 95, DateTimeKind.Local).AddTicks(9791),
                            Email = "korisnik2@befirst.com",
                            Grad = "Sarajevo",
                            Ime = "Ahmed",
                            Komentar = "Ostao bez teksta",
                            PaketId = 1,
                            Prezime = "Hazimovic",
                            UgovorId = 2,
                            VrstaKorisnika = 1
                        });
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.Oprema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojKomada")
                        .HasColumnType("int");

                    b.Property<double>("Cijena")
                        .HasColumnType("float");

                    b.Property<bool>("NaStanju")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Oprema");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrojKomada = 20,
                            Cijena = 35.0,
                            NaStanju = true,
                            Naziv = "Ruter"
                        },
                        new
                        {
                            Id = 2,
                            BrojKomada = 40,
                            Cijena = 45.0,
                            NaStanju = true,
                            Naziv = "Reciever"
                        },
                        new
                        {
                            Id = 3,
                            BrojKomada = 20,
                            Cijena = 15.0,
                            NaStanju = true,
                            Naziv = "Konekcijski"
                        },
                        new
                        {
                            Id = 4,
                            BrojKomada = 20,
                            Cijena = 35.0,
                            NaStanju = true,
                            Naziv = "Modem"
                        });
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.OpremaUposlenikRadnoNalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OpremaId")
                        .HasColumnName("OpremaID")
                        .HasColumnType("int");

                    b.Property<int>("RadniNalogId")
                        .HasColumnName("RadniNalogID")
                        .HasColumnType("int");

                    b.Property<int>("UposlenikId")
                        .HasColumnName("UposlenikID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OpremaId");

                    b.HasIndex("RadniNalogId");

                    b.HasIndex("UposlenikId");

                    b.ToTable("OpremaUposlenikRadnoNalog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OpremaId = 2,
                            RadniNalogId = 1,
                            UposlenikId = 1
                        },
                        new
                        {
                            Id = 2,
                            OpremaId = 2,
                            RadniNalogId = 3,
                            UposlenikId = 1
                        },
                        new
                        {
                            Id = 3,
                            OpremaId = 3,
                            RadniNalogId = 2,
                            UposlenikId = 2
                        });
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.Paket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CaTv")
                        .HasColumnName("CaTV")
                        .HasColumnType("bit");

                    b.Property<int?>("InternetId")
                        .HasColumnType("int");

                    b.Property<int>("PaketNamjenaId")
                        .HasColumnType("int");

                    b.Property<bool?>("Snizen")
                        .HasColumnType("bit");

                    b.Property<int?>("UgovorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InternetId");

                    b.HasIndex("PaketNamjenaId");

                    b.HasIndex("UgovorId");

                    b.ToTable("Paket");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaTv = true,
                            InternetId = 1,
                            PaketNamjenaId = 1,
                            Snizen = true,
                            UgovorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CaTv = true,
                            InternetId = 1,
                            PaketNamjenaId = 2,
                            Snizen = false,
                            UgovorId = 2
                        },
                        new
                        {
                            Id = 3,
                            CaTv = false,
                            InternetId = 3,
                            PaketNamjenaId = 3,
                            Snizen = true,
                            UgovorId = 4
                        },
                        new
                        {
                            Id = 4,
                            CaTv = true,
                            InternetId = 4,
                            PaketNamjenaId = 4,
                            Snizen = false,
                            UgovorId = 2
                        },
                        new
                        {
                            Id = 5,
                            CaTv = true,
                            InternetId = 2,
                            PaketNamjenaId = 1,
                            Snizen = true,
                            UgovorId = 3
                        },
                        new
                        {
                            Id = 6,
                            CaTv = true,
                            InternetId = 5,
                            PaketNamjenaId = 2,
                            Snizen = false,
                            UgovorId = 3
                        });
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.PaketNamjena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaketNamjena");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Studentski paket"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Penzionerski paket"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Obicni paket"
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "Paket za RVI korisnike"
                        });
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.Ponuda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ponuda");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Studentski paket",
                            Opis = "Opis"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Studentski paket",
                            Opis = "Opis"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Studentski paket",
                            Opis = "Opis"
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "Studentski paket",
                            Opis = "Opis"
                        },
                        new
                        {
                            Id = 5,
                            Naziv = "Studentski paket",
                            Opis = "Opis"
                        },
                        new
                        {
                            Id = 6,
                            Naziv = "Studentski paket",
                            Opis = "Opis"
                        },
                        new
                        {
                            Id = 7,
                            Naziv = "Studentski paket",
                            Opis = "Opis"
                        },
                        new
                        {
                            Id = 8,
                            Naziv = "Studentski paket",
                            Opis = "Opis"
                        },
                        new
                        {
                            Id = 9,
                            Naziv = "Studentski paket",
                            Opis = "Opis"
                        },
                        new
                        {
                            Id = 10,
                            Naziv = "Studentski paket",
                            Opis = "Opis"
                        });
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.Pozicije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pozicije");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Software developer",
                            Opis = "Full stack software dev"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Serviser",
                            Opis = "Opis posla za servisera"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Frontend developer",
                            Opis = "Opis posla za frontend dev"
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "User support",
                            Opis = "Opis posla za User support"
                        },
                        new
                        {
                            Id = 5,
                            Naziv = "Sef terena",
                            Opis = "Opis posla za sef terena"
                        });
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.RadniNalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("date");

                    b.Property<int>("KorisnikId")
                        .HasColumnName("KorisnikID")
                        .HasColumnType("int");

                    b.Property<string>("KorisnikIme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnikPrezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisIzvrsenogPosla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisPrijavljenogPosla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("RadniNalog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresa = "a",
                            Datum = new DateTime(2021, 5, 23, 1, 10, 58, 97, DateTimeKind.Local).AddTicks(9352),
                            KorisnikId = 3,
                            KorisnikIme = "Ajla",
                            KorisnikPrezime = "Bise",
                            OpisIzvrsenogPosla = "Zamijenjen resiver",
                            OpisPrijavljenogPosla = "Nestanak programa"
                        },
                        new
                        {
                            Id = 2,
                            Adresa = "a",
                            Datum = new DateTime(2021, 5, 23, 1, 10, 58, 98, DateTimeKind.Local).AddTicks(2051),
                            KorisnikId = 5,
                            KorisnikIme = "Mahir",
                            KorisnikPrezime = "Skula",
                            OpisIzvrsenogPosla = "Priključivanje CaTv",
                            OpisPrijavljenogPosla = "Priključivanje CaTv"
                        },
                        new
                        {
                            Id = 3,
                            Adresa = "a",
                            Datum = new DateTime(2021, 5, 23, 1, 10, 58, 98, DateTimeKind.Local).AddTicks(2102),
                            KorisnikId = 7,
                            KorisnikIme = "Ahmed",
                            KorisnikPrezime = "Hazimovic",
                            OpisIzvrsenogPosla = "Zamijenjen resiver",
                            OpisPrijavljenogPosla = "Loš signal"
                        });
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.Ugovor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrojUgovora")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ugovor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrojUgovora = "44BGFHJJ",
                            Naziv = "Ugovor o radu",
                            Sadrzaj = "Sadrzaj ugovora o radu"
                        },
                        new
                        {
                            Id = 2,
                            BrojUgovora = "11BG45JJ4",
                            Naziv = "Ugovor paket CaTv",
                            Sadrzaj = "Sadrzaj ugovora paket CaTv"
                        },
                        new
                        {
                            Id = 3,
                            BrojUgovora = "8854BGFHJJ",
                            Naziv = "Ugovor paket Internet",
                            Sadrzaj = "Sadrzaj ugovora paket Internet"
                        },
                        new
                        {
                            Id = 4,
                            BrojUgovora = "33RRRHJJ",
                            Naziv = "Ugovor studentski paket",
                            Sadrzaj = "Sadrzaj ugovora studentski paket"
                        });
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.Uloge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("Uloge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Korisnik"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Uposlenik"
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "Serviser"
                        });
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.Uposlenik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId")
                        .HasColumnName("AccountID")
                        .HasColumnType("int");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double>("Plata")
                        .HasColumnType("float");

                    b.Property<int>("PozicijaId")
                        .HasColumnName("PozicijaID")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("UgovorId")
                        .HasColumnName("UgovorID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("PozicijaId");

                    b.HasIndex("UgovorId");

                    b.ToTable("Uposlenik");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 4,
                            Adresa = "Uposlenik Adresa 1",
                            Aktivan = true,
                            BrojTelefona = "063000111",
                            Email = "uposlenik@befirst.com",
                            Grad = "Tuzla",
                            Ime = "UposlenikIme",
                            Plata = 1495.0,
                            PozicijaId = 1,
                            Prezime = "UposlenikPrezime",
                            UgovorId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 5,
                            Adresa = "Uposlenik Adresa 2",
                            Aktivan = true,
                            BrojTelefona = "063000111",
                            Email = "serviser@befirst.com",
                            Grad = "Tuzla",
                            Ime = "ServiserIme",
                            Plata = 1495.0,
                            PozicijaId = 2,
                            Prezime = "ServiserPrezime",
                            UgovorId = 1
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 11,
                            Adresa = "Uposlenik Adresa 2",
                            Aktivan = true,
                            BrojTelefona = "063000111",
                            Email = "serviser@befirst.com",
                            Grad = "Tuzla",
                            Ime = "Nedim",
                            Plata = 1495.0,
                            PozicijaId = 3,
                            Prezime = "Sendro",
                            UgovorId = 1
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 12,
                            Adresa = "Uposlenik Adresa 2",
                            Aktivan = true,
                            BrojTelefona = "063000111",
                            Email = "serviser@befirst.com",
                            Grad = "Tuzla",
                            Ime = "Lejla",
                            Plata = 1495.0,
                            PozicijaId = 3,
                            Prezime = "Bise",
                            UgovorId = 1
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 13,
                            Adresa = "Uposlenik Adresa 2",
                            Aktivan = true,
                            BrojTelefona = "063000111",
                            Email = "serviser@befirst.com",
                            Grad = "Tuzla",
                            Ime = "Nikola",
                            Plata = 1495.0,
                            PozicijaId = 1,
                            Prezime = "Leung",
                            UgovorId = 1
                        });
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.Zahtjev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("KorisnikIme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("Odgovor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Odgovoreno")
                        .HasColumnType("bit");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Pogledno")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Zahtjev");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KorisnikId = 1,
                            KorisnikIme = "Hazim",
                            Naslov = "Prekid programa",
                            Odgovor = "",
                            Odgovoreno = false,
                            Opis = "Jutros od 10:00h prekinuti su svi programi. Molim Vas kad možete doći da popravite?",
                            Pogledno = false
                        },
                        new
                        {
                            Id = 2,
                            KorisnikId = 5,
                            KorisnikIme = "Arman",
                            Naslov = "Istice ugovor",
                            Odgovor = "",
                            Odgovoreno = false,
                            Opis = "Poštovanje, ističe mi uskoro ugovor za paket 88TGHTE, koje papire treba da donesem u prostorije Kablovske da bi produžil isti ugovor?",
                            Pogledno = false
                        },
                        new
                        {
                            Id = 3,
                            KorisnikId = 4,
                            KorisnikIme = "Mahir",
                            Naslov = "Prekid programa",
                            Odgovor = "",
                            Odgovoreno = false,
                            Opis = "Jutros od 11:00h prekinuti su svi programi. Molim Vas kad možete doći da popravite?",
                            Pogledno = false
                        },
                        new
                        {
                            Id = 4,
                            KorisnikId = 3,
                            KorisnikIme = "Ajla",
                            Naslov = "Slab signal",
                            Odgovor = "Kolege serviseri će doći do vas danas u terminu 14:00h. Lp",
                            Odgovoreno = false,
                            Opis = "Zadnjih par dana signal je jako los. Da li bi neko mogao doci da pogleda? Lp",
                            Pogledno = false
                        });
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.Account", b =>
                {
                    b.HasOne("BeFirst.WebAPI.Database.Uloge", "Uloga")
                        .WithMany("Account")
                        .HasForeignKey("UlogaId")
                        .HasConstraintName("FK__Account__UlogeId__267ABA7A")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.Administrator", b =>
                {
                    b.HasOne("BeFirst.WebAPI.Database.Account", "Account")
                        .WithMany("Administrator")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.Internet", b =>
                {
                    b.HasOne("BeFirst.WebAPI.Database.Ugovor", "Ugovor")
                        .WithMany("Internet")
                        .HasForeignKey("UgovorId")
                        .HasConstraintName("FK__Internet__Ugovor__2D27B809")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.Korisnik", b =>
                {
                    b.HasOne("BeFirst.WebAPI.Database.Account", "Account")
                        .WithMany("Korisnik")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK__Korisnik__Accoun__3C69FB99")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeFirst.WebAPI.Database.Paket", "Paket")
                        .WithMany("Korisnik")
                        .HasForeignKey("PaketId")
                        .HasConstraintName("FK__Korisnik__Koment__3A81B327")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeFirst.WebAPI.Database.Ugovor", "Ugovor")
                        .WithMany("Korisnik")
                        .HasForeignKey("UgovorId")
                        .HasConstraintName("FK__Korisnik__Ugovor__3B75D760")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.OpremaUposlenikRadnoNalog", b =>
                {
                    b.HasOne("BeFirst.WebAPI.Database.Oprema", "Oprema")
                        .WithMany("OpremaUposlenikRadnoNalog")
                        .HasForeignKey("OpremaId")
                        .HasConstraintName("FK__OpremaUpo__Oprem__4BAC3F29")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeFirst.WebAPI.Database.RadniNalog", "RadniNalog")
                        .WithMany("OpremaUposlenikRadnoNalog")
                        .HasForeignKey("RadniNalogId")
                        .HasConstraintName("FK__OpremaUpo__Radni__4D94879B")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeFirst.WebAPI.Database.Uposlenik", "Uposlenik")
                        .WithMany("OpremaUposlenikRadnoNalog")
                        .HasForeignKey("UposlenikId")
                        .HasConstraintName("FK__OpremaUpo__Uposl__4CA06362")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.Paket", b =>
                {
                    b.HasOne("BeFirst.WebAPI.Database.Internet", "Internet")
                        .WithMany("Paket")
                        .HasForeignKey("InternetId")
                        .HasConstraintName("FK__Paket__InternetI__300424B4")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeFirst.WebAPI.Database.PaketNamjena", "PaketNamjena")
                        .WithMany()
                        .HasForeignKey("PaketNamjenaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeFirst.WebAPI.Database.Ugovor", "Ugovor")
                        .WithMany("Paket")
                        .HasForeignKey("UgovorId")
                        .HasConstraintName("FK__Paket__UgovorId__30F848ED")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.RadniNalog", b =>
                {
                    b.HasOne("BeFirst.WebAPI.Database.Korisnik", "Korisnik")
                        .WithMany("RadniNalog")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK__RadniNalo__Koris__48CFD27E")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.Uposlenik", b =>
                {
                    b.HasOne("BeFirst.WebAPI.Database.Account", "Account")
                        .WithMany("Uposlenik")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK__Uposlenik__Accou__35BCFE0A")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeFirst.WebAPI.Database.Pozicije", "Pozicija")
                        .WithMany("Uposlenik")
                        .HasForeignKey("PozicijaId")
                        .HasConstraintName("FK__Uposlenik__Pozic__37A5467C")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeFirst.WebAPI.Database.Ugovor", "Ugovor")
                        .WithMany("Uposlenik")
                        .HasForeignKey("UgovorId")
                        .HasConstraintName("FK__Uposlenik__Ugovo__36B12243")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BeFirst.WebAPI.Database.Zahtjev", b =>
                {
                    b.HasOne("BeFirst.WebAPI.Database.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
