version: '3'
services:
#mssql docker
  befirst-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Enterprise
    ports:
      - 1401:1433
    networks:
      - befirstnet

  befirst-api:
    restart: unless-stopped
    build:
      context: .
    environment:
     - ConnectionStrings:connectionpc=Server=befirst-sql,1433;Database=BeFirst_V2;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 5000:80
    networks:
      - befirstnet    
    links:
      - befirst-sql
    depends_on:
      - befirst-sql
      
networks:
  befirstnet:
    driver: bridge      